### ISSUE TITLE
Issue with the deploy

### ISSUE THREAD

**Issue by aarongustafson** [willnap/atmosphere#1]
http://atmosphere-10kapart2016.azurewebsites.net/

**Comment by willnap** [comment]
Hi, sorry about that.
I just deployed the current version at https://willnapier.co/atmosphere-master/, and after I entered my Geocode and Dark Sky keys, it worked. Is the Azure site running the most recent version? It appears to be, but because I can only see the front end, I can't be sure. Is your Dark Sky key working? In testing the Azure site, Geocode appears to be working, but the site is acting like it does when either Dark Sky is down, or the key is either over quota or has been entered incorrectly.
Let me know what you find. If you need either key, let me know and I'll provide them.
Thanks, Will

**Comment by willnap** [comment]
Also, has the .htaccess file been added? For the "Use Current Location" feature to work, the site must be loaded over an HTTPS connection, which is forced by the site's .htaccess.

**Comment by aarongustafson** [comment]
It’s IIS, not Apache. You will need to convert .htaccess to web.config.

**Comment by willnap** [comment]
Sorry about that. Source has been adjusted to support IIS and adding API keys via the Azure site's app settings. App Settings keys ("ERROR_CONTACT" is optional):
<img width="464" alt="screen shot 2016-10-04 at 9 54 23 pm" src="https://cloud.githubusercontent.com/assets/12679632/19100598/84c7ebf0-8a7d-11e6-82f1-04b6d9f7368b.png">
Test Azure site: https://atmosphere.azurewebsites.net

**Comment by aarongustafson** [comment]
@willnap Can you email me the API keys: aarongu@microsoft.com

**Comment by willnap** [comment]
Alright, I sent them.

**Comment by aarongustafson** [comment]
I tucked into your code and got the key names. Don’t worry about responding to my email. https://atmosphere-10kapart2016.azurewebsites.net/
